attach/urls.py
from django.urls import path
from django.conf.urls import url, include
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #login and register urls
    path('',views.lindex,name='index'),
    path('login/',views.login_view, name='login_view'),
    path('register/',views.register, name='register'),
    path('logout/', views.logout_user, name="logout"),
    # path('adminpage/', views.hod, name='adminpage'),
    
    #lecturer urls
    path('lecturer_page/',views.lecturer,name='lecturer'),
    path('viewstudent/',views.viewallstudent,name='allstudent'),
    # path('viewAssessment/',views.viewallassess,name='viewallAssessment'),
    # path('viewsupervisorassess/',views.supervisorassessment,name='viewall'),
    path('lectass/',views.lecturerassement,name='viewall'),
    path('viewcompanydetails/',views.viewCompanydetails,name='allcompanydetails'),
    path('editview/<int:id>', views.getAssess),
    path('logbookdetails/',views.logbookdetails,name='logbookdetails'),
    path('viewlog/<int:id>',views.logbookview),
    path('reportview/',views.reportview,name='reportviews'),
    path('assessed/',views.showassessed,name='assessed'),
    path('lecassess/<int:id>', views.LecAssess),  
    path('lecupdate/<int:id>', views.LecUpdate), 
    path('assessview/<int:id>',views.viewassess),





    #students url
    # path('add',views.add),
    path('companydetails/',views.compdet,name='companydetails'),
    path('student/',views.student,name='student'),
    path('student_det/',views.addStudent,name='new_student'),
    path('elogbook/',views.elogbook,name='logbook'),
    path('new_entry',views.elogbook_entry,name='elogbook'),
    path('view/',views.ViewStudent,name='viewstudent'),
    path('up/',views.model_form_upload,name='report'),
    path('view_report/',views.report,name='view_report'), 
    path('company/',views.addCompany,name='companyde'),
    path('viewCompany/',views.viewCompany,name='ViewCompany'), 
    path('editcompany/<int:id>',views.editcompany),
    path('updatecompany/<int:id>',views.updatecompany),



    #suprvisor urls
    # path('',views.student),
    path('viewlogbook/',views.Logbook,name="viewlogbooks"),
    path('log/<int:id>',views.ViewLogbook),
    path('assessment/',views.viewassessment,name='assess'),
    path('assess/<int:id>',views.view,name="viewassess"),
    path('supervisor_page/',views.supervisor,name='supervisors'),
    path('studentdetails', views.index,name='details'),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    # path('delete/<int:id>', views.destroy),  


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attachment/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('attach.urls')),
    # path('',include('industrial.urls')),
]

attach/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms.widgets import RadioSelect
from attach import myFields
from .myFields import DayOfTheWeekField
from datetime import date
from django.utils import timezone
from datetime import date
from django.core.files import File
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager,PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.db import models
# Create your models here.


class UserManager(BaseUserManager):
    def create_user(self,email,username,first_name,password,**other_fields):
        if not email:
            raise ValueError(_("Users must have an email address"))
        if not username:
            raise ValueError(_("Users must have an unique username"))
        email=self.normalize_email(email)
        user=self.model(email=email,username=username,first_name=first_name,**other_fields)
        user.set_password(password)
        user.save()
    
    def create_superuser(self,email,username,first_name,password,**other_fields):
            other_fields.setdefault('is_staff',True)
            other_fields.setdefault('is_superuser',True)
            other_fields.setdefault('is_active',True)
            if other_fields.get('is_staff') is not True:
                raise ValueError('is_staff is set to False')
            if other_fields.get('is_superuser') is not True:
                raise ValueError('is_superuser is set to False')
            return self.create_user(email,username,first_name,password,**other_fields)

class User(AbstractBaseUser,PermissionsMixin):
    email         = models.EmailField(_('email address'),max_length=60,unique=True)
    username      = models.CharField(max_length=30,unique=True)
    first_name    = models.CharField(max_length=30,blank=True)
    last_name     = models.CharField(max_length=30,blank=True)
    phone_number  = models.CharField(max_length=20, verbose_name='phone number',null=True,blank=True)
    company_name  = models.CharField(max_length=50,blank=True)
    date_joined   = models.DateTimeField(verbose_name='date_joined',auto_now_add=True)
    last_login    = models.DateTimeField(verbose_name='last login',auto_now=True)
    is_admin      = models.BooleanField(default=False)
    is_active     = models.BooleanField(default=True)
    is_staff      = models.BooleanField(default=False)
    is_superuser  = models.BooleanField(default=False)
    is_lecturer = models.BooleanField(default=False)
    is_supervisor = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)

    objects = UserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email','first_name']

    def __str__(self):
        return self.username



# Create your models here.
YEAR_OF_STUDY = (
	('Yr1 Sem2','yr1 Sem2'),
	('yr2 Sem2','yr2 Sem2'),
	('yr3 Sem2','yr3 Sem2'),
	('yr4 Sem2','yr4 Sem2'),
	)
SCHOOL=(
	('SCI','SCI'),
	('SBE','SBE'),
	('SHS','SHS'),
	('SEA','SEA'),
	('SED','SED'),
	('SN','SN'),
	('SPAS','SPAS'),
	('SAFS','SAFS'),
	)
# class User(AbstractUser):
# 	is_admin = models.BooleanField(default=False)
# 	is_lecturer = models.BooleanField(default=False)
# 	is_supervisor = models.BooleanField(default=False)
# 	is_student = models.BooleanField(default=False)


class Staff(models.Model):
	id = models.AutoField(primary_key=True)
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	staff_name = models.CharField(max_length=255)
	phone_number = models.CharField(max_length=50)
	school = models.CharField(max_length=100,choices=SCHOOL)

	class Meta:
		verbose_name_plural = "Staffs"

	def __str__(self):
		return self.staff_name



class StudentDetails(models.Model):
	id = models.AutoField(primary_key=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	student_name = models.CharField(max_length=255)
	coursename = models.CharField(max_length=255)
	regno = models.CharField(max_length=100)
	year_of_study = models.CharField(max_length=100,choices=YEAR_OF_STUDY)
	school = models.CharField(max_length=100,choices=SCHOOL)
	created = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		return self.regno	

class CompDetails(models.Model):
	id = models.AutoField(primary_key=True)
	student = models.ForeignKey(StudentDetails,on_delete=models.DO_NOTHING)
	s_fullname = models.CharField(max_length=255)
	registration_no = models.CharField(max_length=255)
	phone_number = models.CharField(max_length=100)
	company_name = models.CharField(max_length=200)
	address = models.TextField()
	county = models.CharField(max_length=200)
	company_phone_no = models.CharField(max_length=255)
	supervisor_name = models.CharField(max_length=255)

	def __str__(self):
		return self.s_fullname



class Elogbook(models.Model):
	id = models.AutoField(primary_key=True)
	student = models.ForeignKey(StudentDetails,on_delete=models.DO_NOTHING)
	workdone = models.TextField()
	skills = models.TextField(default=1)
	mdate = models.DateField(null=False, blank=False)
	dayOfTheWeek = myFields.DayOfTheWeekField()
	remarks = models.TextField()
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = 'Elogbook'
		verbose_name_plural = "Elogbooks"

	def __str__(self):	
		return self.workdone

class Document(models.Model):		
	student = models.ForeignKey(StudentDetails,on_delete=models.DO_NOTHING)
	document = models.FileField(upload_to='document/')
	uploaded_at = models.DateTimeField(auto_now_add=True)


class Student(models.Model):
	GENDER_CHOICE = (
		('male','male'),
		('female','female'),
		)
	PERFOMANCE_CHOICE = (
		('excellent','excellent'),
		('good','good'),
		('average','average'),
		('fair','fair'),
		('poor','poor'),
		)
	STATUS = (
		('assessed','assessed'),
		('notassessed','notassessed'),
		)
	s_fullname = models.CharField(max_length=255)
	registration_no = models.CharField(max_length=255)
	phone_number = models.CharField(max_length=100)
	company_name = models.CharField(max_length=200)
	address = models.TextField()
	county = models.CharField(max_length=200)
	company_phone_no = models.CharField(max_length=255)
	supervisor_name = models.CharField(max_length=255)
	gender = models.CharField(max_length=100,choices=GENDER_CHOICE)
	period_from = models.DateField(null=True, blank=True)
	period_to = models.DateField(null=True,blank=True)
	punctual = models.CharField(max_length=100,choices=PERFOMANCE_CHOICE)
	regulations = models.CharField(max_length=100,choices=PERFOMANCE_CHOICE)
	workmanship = models.CharField(max_length=100,choices=PERFOMANCE_CHOICE)
	workout = models.CharField(max_length=100,choices=PERFOMANCE_CHOICE)
	adaptability = models.CharField(max_length=100,choices=PERFOMANCE_CHOICE)
	commu = models.CharField(max_length=100,choices=PERFOMANCE_CHOICE)
	reliability = models.CharField(max_length=100,choices=PERFOMANCE_CHOICE)
	team_work = models.CharField(max_length=100,choices=PERFOMANCE_CHOICE)
	overall_assessment = models.CharField(max_length=100,choices=PERFOMANCE_CHOICE)
	general_remarks = models.TextField()
	assessed_by = models.CharField(max_length=255,blank=True)
	status = models.CharField(max_length=255,choices=STATUS, default="notassessed")
	position = models.CharField(max_length=255,blank=True)
	mdate = models.DateField(null=True,blank=True)
	class Meta:
		db_table = "student"

class Lecturer(models.Model):		
	GENDER_CHOICE = (
		('male','male'),
		('female','female'),
		)
	PERFOMANCE_CHOICE = (
		('excellent','excellent'),
		('good','good'),
		('average','average'),
		('fair','fair'),
		('poor','poor'),
		)
	STATUS = (
		('assessed','assessed'),
		('notassessed','notassessed'),
		)
	s_fullname = models.CharField(max_length=255)
	registration_no = models.CharField(max_length=255)
	phone_number = models.CharField(max_length=100)
	company_name = models.CharField(max_length=255)
	address = models.TextField()
	county = models.CharField(max_length=255)
	company_phone_no = models.CharField(max_length=50)
	supervisor_name = models.CharField(max_length=255)
	gender = models.CharField(max_length=255,choices=GENDER_CHOICE)
	period_from = models.DateField(null=True, blank=True)
	period_to = models.DateField(null=True,blank=True)
	punctual = models.CharField(max_length=255,choices=PERFOMANCE_CHOICE)
	regulations = models.CharField(max_length=255,choices=PERFOMANCE_CHOICE)
	workmanship = models.CharField(max_length=255,choices=PERFOMANCE_CHOICE)
	workout = models.CharField(max_length=255,choices=PERFOMANCE_CHOICE)
	adaptability = models.CharField(max_length=255,choices=PERFOMANCE_CHOICE)
	commu = models.CharField(max_length=255,choices=PERFOMANCE_CHOICE)
	reliability = models.CharField(max_length=255,choices=PERFOMANCE_CHOICE)
	team_work = models.CharField(max_length=255,choices=PERFOMANCE_CHOICE)
	overall_assessment = models.CharField(max_length=255,choices=PERFOMANCE_CHOICE)
	general_remarks = models.TextField()
	assessed_by = models.CharField(max_length=255)
	status = models.CharField(max_length=255,choices=STATUS, default="notassessed")
	position = models.CharField(max_length=255)
	mdate = models.DateField(null=True,blank=True)
	class Meta:
		db_table = "lecturer"

attach/templates/lectures/assessed.html
<!-- //templates/show.html -->
{% extends "lectures/index.html" %}
 
{% block title %}Employee Records{% endblock title %}
 
{% block content %}
{% if request.user.is_authenticated  and user.is_lecturer %}
  <section style="margin-top:50px" class="home-section">
    <div class="home-content">
      <div class="col-md-12">
     <!-- <span><a href="" class="btn btn-primary">Add New Record</a></span>   -->
<h4 style="margin-left:50px">List Of Students Not Assessed By Lecturer</h4><br>
        <div class="table">
  <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
                <!-- <th><input type="checkbox" id="checkall" /></th> -->
                <th style="width:20px !important;display: none;">ID</th>
                <th>Student Name</th>
                <th>Registration No</th>
                <th>Supervisor Name</th>
                <th>Supervisor Phone</th>                
                <th>Status</th>
                <th>Assess</th>
                <!-- <th>View Assessment</th> -->
             </thead>
   <tbody>
   {% for student in students %}  
    <tr>  
     <td>{{student.s_fullname }}</td>
     <td>{{ student.registration_no}}</td> 
     <td>{{student.supervisor_name}}</td>   
     <td>{{student.company_phone_no}}</td>
     <td><button class="btn btn-pill btn-danger">{{student.status}}</button></td>
     <!-- <td></td> -->
     <td class="col-sm-1"><p data-placement="top" data-toggle="tooltip" title="Edit"><a style="margin-left: 25px" href="/lecassess/{{ student.id }}" class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" ><span  class="bx bx-detail"></span></a></p></td> 

     
     <td></td>
     
   {% endfor %} 
      </tr>  
   </tbody>
         
  </table>

    </div>
    </div>
  </section>
   {% else %}
  <p>You are Not allowed to access this page</p>
{% endif %}

{% endblock content %}
<!--   <section class="home-section">
    <div class="home-content">

    </div>
  </section> -->

attach/templates/lectures/assessment.html
<!-- //templates/edit.html -->
{% extends "lectures/index.html" %}
 {% load static %}
{% block title %}Add New Employee Records{% endblock title %}
 
{% block content %}
{% if request.user.is_authenticated  and user.is_lecturer %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Multiple user login</title>
  </head>
  <style type="text/css">
    body {
    color: #000;
    overflow-x: hidden;
    height: 100%;
    background-image: url("https://i.imgur.com/GMmCQHC.png");
    background-repeat: no-repeat;
    background-size: 100% 100%
}

.card {
    padding: 30px 40px;
    margin-top: 60px;
    margin-left: 230px !important;
    margin-bottom: 60px;
    border: none !important;
    box-shadow: 0 6px 12px 0 rgba(0, 0, 0, 0.2)
}

.blue-text {
    color: #00BCD4
}

.form-control-label {
    margin-bottom: 0
}
.form-group{
    font-size: 15px !important;
    font-weight: 200 !important
}
label{
    font-size: 13px;
    text-align: left !important;
}
input,
textarea,
button {
    padding: 8px 15px;
    border-radius: 5px !important;
    margin: 5px 0px;
    box-sizing: border-box;
    border: 1px solid #ccc;
    font-size: 18px !important;
    font-weight: 300
}

input:focus,
textarea:focus {
    -moz-box-shadow: none !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
    border: 1px solid #00BCD4;
    outline-width: 0;
    font-weight: 400
}

.btn-block {
    text-transform: uppercase;
    font-size: 15px !important;
    font-weight: 400;
    height: 43px;
    cursor: pointer
}

.btn-block:hover {
    color: #fff !important
}

button:focus {
    -moz-box-shadow: none !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
    outline-width: 0
}
  </style>
  <body>
<form method="POST" class="post-form"  action="/update/{{student.id}}">  
   {% csrf_token %}  
  <div class="container">  
 <div class="container-fluid px-1 py-5 mx-auto">
    <div class="row">
        <div class="col-xl-7 col-lg-12 col-md-9 col-11 text-center">
            <h3 style="margin-left: 170px !important;">{{student.s_fullname}} <br><br>Final Lecturer Assessment Form</h3>
            <!-- <h4 style="margin-left:340px;">(This form is to be filled by the Industry Based Supervisor)</h4> -->
            <p class="blue-text"></p>
            <div class="card" style="width:900px">
                <h5 class="text-center mb-4"></h5>
                <!-- <form class="form-card" onsubmit="event.preventDefault()"> -->
                    <div class="row justify-content-between text-left">
            
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Student fullname:<span class="text-danger"> *</span></label>
                          <!-- <input required name="s_fullname" value="{{superassess.s_fullname}}" type="text" multiple class="form-control"> -->
                          <input type="text" class="form-control" name="s_fullname" id="id_s_fullname" required maxlength="150" value="{{ student.s_fullname }}" /> 
                        </div> 
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Phone No:<span class="text-danger"> *</span></label>
                          <!-- <input required name="s_fullname" value="{{superassess.s_fullname}}" type="text" multiple class="form-control"> -->
                          <input type="text" class="form-control" name="phone_number" id="id_phone_number" required maxlength="150" value="{{ student.phone_number }}" />  
                        </div>
                    </div>    
                    <div class="row justify-content-between text-left">  
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label class="form-control-label px-3">Gender</label>
                            <input type="text" class="form-control" placeholder="gender" value="{{student.gender}}" name='gender'>
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Reg no:<span class="text-danger"> *</span></label>
                          <input type="text" class="form-control" name="registration_no" id="id_registration_no" required maxlength="150" value="{{ student.registration_no }}" /> 
                        </div> 
                   </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Company Name:<span class="text-danger"> *</span></label>
                          <input type="text" class="form-control" name="company_name" id="id_company_name" required maxlength="150" value="{{ student.company_name}}" />
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Address:<span class="text-danger"> *</span></label>
                          <input type="text" class="form-control" name="address" id="id_address" required maxlength="150" value="{{ student.address }}" />
                        </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Supervisor Name:<span class="text-danger"> *</span></label>
                          <input type="text" class="form-control" name="supervisor_name" id="id_supervisor_name" required maxlength="150" value="{{ student.supervisor_name }}" />
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Supervisor Phone:<span class="text-danger"> *</span></label>
                         <input type="text" class="form-control" name="company_phone_no" id="id_company_phone_no" required maxlength="150" value="{{ student.company_phone_no }}" /> 
                        </div>  
                    </div>
                    <div class="row justify-content-between text-left">  
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label class="form-control-label px-3">Punctuality</label>
                            <input type="text" class="form-control"  value="{{student.punctual}}" name='gender'>
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Regulations:<span class="text-danger"> *</span></label>
                          <input type="text" class="form-control" required maxlength="150" value="{{ student.regulations}}" /> 
                        </div> 
                   </div>
                   <div class="row justify-content-between text-left">  
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label class="form-control-label px-3">Workmanship</label>
                            <input type="text" class="form-control"  value="{{student.workmanship}}" name='gender'>
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">WorkOut:<span class="text-danger"> *</span></label>
                          <input type="text" class="form-control"  required maxlength="150" value="{{ student.workout }}" /> 
                        </div> 
                   </div>
                   <div class="row justify-content-between text-left">  
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label class="form-control-label px-3">Adaptability:</label>
                            <input type="text" class="form-control"  value="{{student.adaptability}}" >
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Communacation:<span class="text-danger"> *</span></label>
                          <input type="text" class="form-control" value="{{ student.commu }}" /> 
                        </div> 
                   </div>
                   <div class="row justify-content-between text-left">  
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label class="form-control-label px-3">Reliability:</label>
                            <input type="text" class="form-control"  value="{{student.reliability}}" >
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Team Work:<span class="text-danger"> *</span></label>
                          <input type="text" class="form-control" value="{{ student.team_work }}" /> 
                        </div> 
                   </div>
                   <div class="row justify-content-between text-left">  
                        <div class="form-group col-sm-6 flex-column d-flex">
                            <label class="form-control-label px-3">Overall Assessment:</label>
                            <input type="text" class="form-control"  value="{{student.overall_assessment}}" >
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Communacation:<span class="text-danger"> *</span></label>
                          <input type="text" class="form-control" value="{{ student.commu }}" /> 
                        </div> 
                   </div>

                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">General Remarks<span class="text-danger"> *</span></label>
                           <input type="text" class="form-control" name="general_remarks" id="id_general_remarks" required maxlength="150" value="{{ student.general_remarks }}" />
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Assessed By:<span class="text-danger"> *</span></label>
                          <input type="text" class="form-control" name="assessed_by" id="id_assessed_by" required maxlength="150" value="{{ student.assessed_by}}" />
                        </div>
                    </div>
                    <div class="row justify-content-between text-left">
                         
                        <!-- <div class="form-group col-sm-6 flex-column d-flex">
                            <label class="form-control-label px-3">Status:<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" name="status" id="id_status"  maxlength="15" value="{{ superassess.status }}" />
                        </div> -->
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex">
                        <label class="form-control-label px-3">Position/Designation:<span class="text-danger"> *</span></label>
                          <input type="text" class="form-control" name="position" id="id_position" required maxlength="150" value="{{ student.position }}" /> 
                        </div>
                        <div class="form-group col-sm-6 flex-column d-flex">
                          <label class="form-control-label px-3">Date:<span class="text-danger"> *</span></label>
                          <input type="text" class="form-control" name="mdate" id="id_mdate" required maxlength="15" value="{{ student.mdate }}" />
                          <!-- <input required name="mdate" value="{{superassess.mdate}}" id="mdate" type="date" multiple class="form-control"> -->
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

</div>
</div>
</section>

</body>
   {% else %}
  <p>You are Not allowed to access this page</p>
{% endif %}
{% endblock content %}   

attach/templates/lectures/index.html
{% if request.user.is_authenticated  and user.is_lecturer %}
<!DOCTYPE html>
<!-- Created by CodingLab |www.youtube.com/CodingLabYT-->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    {% load static %}  
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
 
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
  <link rel="stylesheet" href="{% static 'new/style.css' %}">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="sideba">
    <div class="logo-details">
      <i class='bx bxl-c-plus-plus'></i>
      <span class="logo_name">IAMS</span>
    </div>
    <ul class="nav-links">
      <li>
        <a href="{% url 'allstudent'%}">
          <i class='bx bx-grid-alt' ></i>
          <span class="link_name">Student Details</span>
        </a>
      </li>
      <li>
        <a href="{% url 'allcompanydetails'%}">
          <i class='bx bx-grid-alt' ></i>
          <span class="link_name">Company Details</span>
        </a>
      </li>
      <li>
        <div class="iocn-link">
          <a href="{% url 'viewall'%}">
            <i class='bx bx-detail' ></i>
            <span class="link_name">Supervisor Assessment</span>
          </a>
        </div>
      </li>
      <li>
        <div class="iocn-link">
          <a href="{% url 'assessed'%}">
            <i class='bx bx-detail' ></i>
            <span class="link_name">Lecturer Assessment</span>
          </a>
        </div>
      </li>
      <li>
        <div class="iocn-link">
          <a href="{% url 'logbookdetails' %}">
            <i class='bx bx-book-open' ></i>
            <span class="link_name">E-Logbook</span>
          </a>
        </div>
      </li>
      <li>
        <a href="{% url 'reportviews' %}">
          <i class='bx bx-file-blank' ></i>
          <span class="link_name">Report</span>
        </a>
      </li>

    <div class="profile-details">
      <div class="profile-content">
        <!--<img src="image/profile.jpg" alt="profileImg">-->
      </div>
      <div class="name-job">
        
        <div class="profile_name">{{request.user}}</div>
        <div class="job">Company Name: {{ user.company_name }}</div>

      </div>
      <a href="{% url 'logout'%}"><i class='bx bx-log-out-circle' style="font-size:26px;color:white;margin-right: 20px;" ></i></a>
    </div>
  </li>
</ul>
  </div>
  

    {% block content %}{% endblock %}
  <script>

  $(document).ready(function() {
    $('#bootstrapdatatable').DataTable({     
      "aLengthMenu": [[7], [7]],
        "iDisplayLength": 7
       } 
    );
} );
  </script>
</body>
</html>

   {% else %}
  <p>You are Not allowed to access this page</p>
{% endif %}